export const NATIONALITIES = [
  { code: "KR", name: "대한민국" },
  { code: "US", name: "미국" },
  { code: "JP", name: "일본" },
  { code: "CN", name: "중국" },
  { code: "GB", name: "영국" },
  { code: "FR", name: "프랑스" },
  { code: "DE", name: "독일" },
  { code: "CA", name: "캐나다" },
  { code: "AU", name: "호주" },
  { code: "VN", name: "베트남" },
  { code: "TH", name: "태국" },
  { code: "PH", name: "필리핀" },
  { code: "ID", name: "인도네시아" },
  { code: "SG", name: "싱가포르" },
  { code: "MY", name: "말레이시아" },
  { code: "TW", name: "대만" },
  { code: "HK", name: "홍콩" },
  { code: "IN", name: "인도" },
  { code: "RU", name: "러시아" },
  { code: "BR", name: "브라질" },
  { code: "MX", name: "멕시코" },
  { code: "ES", name: "스페인" },
  { code: "IT", name: "이탈리아" },
  { code: "NL", name: "네덜란드" },
  { code: "CH", name: "스위스" },
  { code: "SE", name: "스웨덴" },
  { code: "NO", name: "노르웨이" },
  { code: "NZ", name: "뉴질랜드" },
];

export default NATIONALITIES;
