# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
    begin
      delete_keychain(name: "temp_keychain") if File.exist?(File.expand_path("~/Library/Keychains/temp_keychain-db"))

      create_keychain(
        name: "temp_keychain",
        password: "temp_password",
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )

      match(
        type: "appstore",
        readonly: true,
        keychain_name: "temp_keychain",
        keychain_password: "temp_password"
      )

      disable_automatic_code_signing(path: "ios/app.xcodeproj")

      update_code_signing_settings(
        use_automatic_signing: false,
        path: "ios/app.xcodeproj",
        code_sign_identity: "Apple Distribution",
        profile_name: "match AppStore com.earseo.earseo",
        team_id: ENV["APPLE_TEAM_ID"]
      )

      app_store_build_number = latest_testflight_build_number(
        api_key: app_store_connect_api_key(
          key_id: ENV["APPSTORE_KEY_ID"],
          issuer_id: ENV["APPSTORE_ISSUER_ID"],
          is_key_content_base64: true,
          key_content: ENV["APPSTORE_API_KEY_CONTENT"]
        ),
        app_identifier: ENV["APPLE_APP_IDENTIFIER"]
      )

      increment_build_number(
        build_number: (app_store_build_number.to_i + 1).to_s,
        xcodeproj: "ios/app.xcodeproj"
      )


      build_app(
        scheme: "app",
        workspace: "ios/app.xcworkspace",
        export_method: "app-store",
        clean: true
      )

      upload_to_testflight(
        skip_waiting_for_build_processing: true,
        api_key: app_store_connect_api_key(
          key_id: ENV["APPSTORE_KEY_ID"],
          issuer_id: ENV["APPSTORE_ISSUER_ID"],
          is_key_content_base64: true,
          key_content: ENV["APPSTORE_API_KEY_CONTENT"]
          )
      )

      package_json = JSON.parse(File.read("../package.json"))
      version = package_json["version"]

      git_tag = "v#{version}-#{app_store_build_number.to_i + 1}"

      sh("git tag #{git_tag}")
      sh("git push origin #{git_tag}")

    ensure
      delete_keychain(name: "temp_keychain") if File.exist?(File.expand_path("~/Library/Keychains/temp_keychain-db"))
    end
  end
end
